Subtitle Display Tool: detail::invalid_iterator Class Reference
detail::invalid_iterator Class Reference
exception indicating errors with iterators
#include <json.hpp>
Static Public Member Functions
template<typename BasicJsonContext , enable_if_t< is_basic_json_context< BasicJsonContext >::value, int > = 0>
static invalid_iterator create (int id_, const std::string &what_arg, BasicJsonContext context)
Additional Inherited Members
Public Member Functions inherited from detail::exception
const char * what () const noexcept override
returns the explanatory string
Public Attributes inherited from detail::exception
const int id
the id of the exception
Protected Member Functions inherited from detail::exception
exception (int id_, const char *what_arg)
Static Protected Member Functions inherited from detail::exception
static std::string name (const std::string &ename, int id_)
static std::string diagnostics (std::nullptr_t)
template<typename BasicJsonType >
static std::string diagnostics (const BasicJsonType *leaf_element)
Detailed Description
exception indicating errors with iterators
See also
https://json.nlohmann.me/api/basic_json/invalid_iterator/
Member Function Documentation
create()
template<typename BasicJsonContext , enable_if_t< is_basic_json_context< BasicJsonContext >::value, int > = 0> static invalid_iterator detail::invalid_iterator::create (int id_, const std::string & what_arg, BasicJsonContext context) inline static
References detail::concat(), detail::exception::diagnostics(), and detail::exception::name().
Referenced by basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::basic_json(), basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::erase(), basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::insert(), detail::iter_impl< BasicJsonType >::key(), detail::iter_impl< BasicJsonType >::operator*(), detail::iter_impl< BasicJsonType >::operator+=(), detail::iter_impl< BasicJsonType >::operator-(), detail::iter_impl< BasicJsonType >::operator->(), detail::iter_impl< BasicJsonType >::operator<(), detail::iter_impl< BasicJsonType >::operator==(), detail::iter_impl< BasicJsonType >::operator[](), and basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType, CustomBaseClass >::update().
The documentation for this class was generated from the following file:
Subtitle-Display-Tool/vendor/nlohmann/json.hpp