Subtitle Display Tool: Subtitle Class Reference
Subtitle Class Reference
#include <Subtitle.h>
Public Member Functions
Subtitle (std::string dialogue, Styles styles={}, double startTime=0.0)
float GetFontSize () const
std::string GetDialogue () const
Vec2i GetPosition () const
Vec4i GetColor () const
Vec4i GetBackgroundColor () const
Font GetFont () const
double GetLifetime () const
double GetStartTime () const
Styles GetStyles () const
Constructor & Destructor Documentation
Subtitle()
Subtitle::Subtitle (std::string dialogue, Styles styles = {}, double startTime = 0.0)
Member Function Documentation
GetBackgroundColor()
Vec4i Subtitle::GetBackgroundColor () const inline
References Styles::bgColor.
Referenced by Window::Window().
GetColor()
Vec4i Subtitle::GetColor () const inline
References Styles::fontColor.
Referenced by Window::Window().
GetDialogue()
std::string Subtitle::GetDialogue () const inline
Referenced by Window::GetWindowDimensions(), and Window::Window().
GetFont()
Font Subtitle::GetFont () const inline
Referenced by Window::GetWindowDimensions(), and Window::Window().
GetFontSize()
float Subtitle::GetFontSize () const inline
References Styles::fontSize.
Referenced by Window::GetWindowDimensions(), and Window::Window().
GetLifetime()
double Subtitle::GetLifetime () const inline
References Styles::lifetime.
Referenced by Window::IsVisible().
GetPosition()
Vec2i Subtitle::GetPosition () const inline
References Styles::position.
GetStartTime()
double Subtitle::GetStartTime () const inline
Referenced by Window::IsVisible().
GetStyles()
Styles Subtitle::GetStyles () const inline
Referenced by Window::GetWindowDimensions(), and Window::Window().
The documentation for this class was generated from the following files:
Subtitle-Display-Tool/src/Subtitle.h
Subtitle-Display-Tool/src/Subtitle.cpp