Subtitle Display Tool: Window Class Reference
Window Class Reference
#include <Window.h>
Public Member Functions
Window (std::string dialogue, double creationTime)
Window (Subtitle subtitle)
Window (const Window &other)
Window (Window &&other) noexcept
Window & operator= (const Window &other)
Window & operator= (Window &&other) noexcept
~Window ()
Vec2f GetWindowDimensions () const
void Draw () const
bool IsVisible () const
Detailed Description
Container for a subtitle and the data and methods needed to draw that subtitle to the screen.
Constructor & Destructor Documentation
Window() [1/4]
Window::Window (std::string dialogue, double creationTime)
References Window().
Referenced by Window().
Window() [2/4]
Window::Window (Subtitle subtitle)
References DropShadowSettings::color, DEFAULT_SPACING, Subtitle::GetBackgroundColor(), Subtitle::GetColor(), Subtitle::GetDialogue(), Subtitle::GetFont(), Subtitle::GetFontSize(), Subtitle::GetStyles(), GetWindowDimensions(), DropShadowSettings::offset, Styles::outline, OUTLINE_SHADER_PATH, OutlineSettings::outlineColor, OutlineSettings::outlineSize, SDF_SHADER_PATH, Styles::shadow, SHADOW_SHADER_PATH, DropShadowSettings::values, OutlineSettings::values, Vec4i::w, Window(), Vec2f::x, Vec4i::x, Vec2f::y, Vec4i::y, and Vec4i::z.
Window() [3/4]
Window::Window (const Window & other)
References Window().
Window() [4/4]
Window::Window (Window && other) noexcept
References Window().
~Window()
Window::~Window ()
Member Function Documentation
Draw()
void Window::Draw () const
Draws the Window's associated texture to whatever texture is active at the time of call (in general, the main framebuffer).
References IsVisible().
GetWindowDimensions()
Vec2f Window::GetWindowDimensions () const
Returns the width and height of the window, calculated to the exact size of the text + any graphical effects.
References DEFAULT_SPACING, Subtitle::GetDialogue(), Subtitle::GetFont(), Subtitle::GetFontSize(), Subtitle::GetStyles(), Styles::outline, and OutlineSettings::outlineSize.
Referenced by Window().
IsVisible()
bool Window::IsVisible () const
Returns a bool describing whether the window should be drawn at the current time, depending on time of creation and lifetime.
References Subtitle::GetLifetime(), and Subtitle::GetStartTime().
Referenced by Draw().
operator=() [1/2]
Window & Window::operator= (const Window & other)
operator=() [2/2]
Window & Window::operator= (Window && other) noexcept
The documentation for this class was generated from the following files:
Subtitle-Display-Tool/src/Window.h
Subtitle-Display-Tool/src/Window.cpp