Subtitle Display Tool: TkinterExample Namespace Reference
TkinterExample Namespace Reference
Classes
class CollapsibleFrame
Functions
def clicked (data)
def restart_connection ()
def on_closing ()
def update_format_options (*args)
def create_label_entry (parent, text, default_value="")
def create_font_path_combobox (parent, text)
def select_file (entry)
def get_style_data (fields)
def create_style_fields (parent)
Variables
string HOST = "localhost"
int PORT = 9999
string EXE_PATH = '..\\..\\bin\\Debug\\Subtitle-Display-Tool.exe'
string FONT_DIR = "C:\\Windows\\Fonts"
tuple FONT_EXTENSIONS = ('.ttf', '.otf')
string DEFAULT_FONT_SIZE = "54"
string DEFAULT_POSITION = "250"
string DEFAULT_FONT_COLOR = "255"
string DEFAULT_BG_COLOR = "0"
string DEFAULT_OUTLINE_SIZE = "2.0"
string DEFAULT_OUTLINE_COLOR = "0.0"
string DEFAULT_DROP_SHADOW_COLOR = "0.0"
string DEFAULT_DROP_SHADOW_OFFSET = "1"
string DEFAULT_DROP_SHADOW_BLUR_STRENGTH = "1"
proc = subprocess.Popen([EXE_PATH, str(PORT)])
app = Tk()
format_var = StringVar()
format_label = Label(app, text="Select Subtitle Format:")
row
column
padx
pady
format_menu = ttk.Combobox(app, textvariable=format_var, values=["Simple", "Advanced", "File"])
simple_frame = LabelFrame(app, text="Simple Format Options", padx=10, pady=10)
simple_dialogue_label = Label(simple_frame, text="Dialogue:")
fill
simple_dialogue_entry = Entry(simple_frame)
simple_btn
advanced_frame = LabelFrame(app, text="Advanced Format Options", padx=10, pady=10)
advanced_dialogue_label = Label(advanced_frame, text="Dialogue:")
advanced_dialogue_entry = Entry(advanced_frame)
def advanced_fields = create_style_fields(advanced_frame)
advanced_lifetime_label = Label(advanced_frame, text="Lifetime:")
advanced_lifetime_entry = Entry(advanced_frame)
advanced_btn
file_frame = LabelFrame(app, text="File Format Options", padx=10, pady=10)
file_path_frame = Frame(file_frame)
file_path_label = Label(file_path_frame, text="File Path:", width=20, anchor='w')
side
LEFT
file_path_entry = Entry(file_path_frame)
expand
file_path_button = Button(file_path_frame, text="Browse", command=lambda: select_file(file_path_entry))
def file_fields = create_style_fields(file_frame)
file_btn
btn6
btn_restart = Button(app, text="Restart Connection", command=restart_connection)
sticky
Function Documentation
clicked()
def TkinterExample.clicked (data)
create_font_path_combobox()
def TkinterExample.create_font_path_combobox (parent, text)
Referenced by create_style_fields().
create_label_entry()
def TkinterExample.create_label_entry (parent, text, default_value = "")
Referenced by create_style_fields().
create_style_fields()
def TkinterExample.create_style_fields (parent)
References create_font_path_combobox(), and create_label_entry().
get_style_data()
def TkinterExample.get_style_data (fields)
on_closing()
def TkinterExample.on_closing ()
restart_connection()
def TkinterExample.restart_connection ()
select_file()
def TkinterExample.select_file (entry)
update_format_options()
def TkinterExample.update_format_options (* args)
Variable Documentation
advanced_btn
TkinterExample.advanced_btn
Initial value:
 =  Button(advanced_frame, text="Create Advanced Window", command=lambda: clicked({
     "mode": "advanced",
     "data": {
         "dialogue": advanced_dialogue_entry.get(),
         "styles": {**get_style_data(advanced_fields), "lifetime": float(advanced_lifetime_entry.get())}
     }
 }))
advanced_dialogue_entry
TkinterExample.advanced_dialogue_entry = Entry(advanced_frame)
advanced_dialogue_label
TkinterExample.advanced_dialogue_label = Label(advanced_frame, text="Dialogue:")
advanced_fields
def TkinterExample.advanced_fields = create_style_fields(advanced_frame)
advanced_frame
TkinterExample.advanced_frame = LabelFrame(app, text="Advanced Format Options", padx=10, pady=10)
advanced_lifetime_entry
TkinterExample.advanced_lifetime_entry = Entry(advanced_frame)
advanced_lifetime_label
TkinterExample.advanced_lifetime_label = Label(advanced_frame, text="Lifetime:")
app
TkinterExample.app = Tk()
btn6
TkinterExample.btn6
Initial value:
 =  Button(file_frame, text="Create Window showcasing WebVTT file support", command=lambda: clicked({
     "mode": "file",
     "data": {"filePath": "./test_files/example.vtt", "styles": get_style_data(file_fields)}
 }))
btn_restart
TkinterExample.btn_restart = Button(app, text="Restart Connection", command=restart_connection)
column
TkinterExample.column
DEFAULT_BG_COLOR
string TkinterExample.DEFAULT_BG_COLOR = "0"
DEFAULT_DROP_SHADOW_BLUR_STRENGTH
string TkinterExample.DEFAULT_DROP_SHADOW_BLUR_STRENGTH = "1"
DEFAULT_DROP_SHADOW_COLOR
string TkinterExample.DEFAULT_DROP_SHADOW_COLOR = "0.0"
DEFAULT_DROP_SHADOW_OFFSET
string TkinterExample.DEFAULT_DROP_SHADOW_OFFSET = "1"
DEFAULT_FONT_COLOR
string TkinterExample.DEFAULT_FONT_COLOR = "255"
DEFAULT_FONT_SIZE
string TkinterExample.DEFAULT_FONT_SIZE = "54"
DEFAULT_OUTLINE_COLOR
string TkinterExample.DEFAULT_OUTLINE_COLOR = "0.0"
DEFAULT_OUTLINE_SIZE
string TkinterExample.DEFAULT_OUTLINE_SIZE = "2.0"
DEFAULT_POSITION
string TkinterExample.DEFAULT_POSITION = "250"
EXE_PATH
string TkinterExample.EXE_PATH = '..\\..\\bin\\Debug\\Subtitle-Display-Tool.exe'
expand
TkinterExample.expand
file_btn
TkinterExample.file_btn
Initial value:
 =  Button(file_frame, text="Load Subtitles from File", command=lambda: clicked({
     "mode": "file",
     "data": {"filePath": file_path_entry.get(), "styles": get_style_data(file_fields)}
 }))
file_fields
def TkinterExample.file_fields = create_style_fields(file_frame)
file_frame
TkinterExample.file_frame = LabelFrame(app, text="File Format Options", padx=10, pady=10)
file_path_button
TkinterExample.file_path_button = Button(file_path_frame, text="Browse", command=lambda: select_file(file_path_entry))
file_path_entry
TkinterExample.file_path_entry = Entry(file_path_frame)
file_path_frame
TkinterExample.file_path_frame = Frame(file_frame)
file_path_label
TkinterExample.file_path_label = Label(file_path_frame, text="File Path:", width=20, anchor='w')
fill
TkinterExample.fill
FONT_DIR
string TkinterExample.FONT_DIR = "C:\\Windows\\Fonts"
FONT_EXTENSIONS
tuple TkinterExample.FONT_EXTENSIONS = ('.ttf', '.otf')
format_label
TkinterExample.format_label = Label(app, text="Select Subtitle Format:")
format_menu
TkinterExample.format_menu = ttk.Combobox(app, textvariable=format_var, values=["Simple", "Advanced", "File"])
format_var
TkinterExample.format_var = StringVar()
HOST
string TkinterExample.HOST = "localhost"
LEFT
TkinterExample.LEFT
padx
TkinterExample.padx
pady
TkinterExample.pady
PORT
int TkinterExample.PORT = 9999
proc
TkinterExample.proc = subprocess.Popen([EXE_PATH, str(PORT)])
row
TkinterExample.row
side
TkinterExample.side
simple_btn
TkinterExample.simple_btn
Initial value:
 =  Button(simple_frame, text="Create Simple Window", command=lambda: clicked({
     "mode": "simple",
     "data": {"dialogue": simple_dialogue_entry.get()}
 }))
simple_dialogue_entry
TkinterExample.simple_dialogue_entry = Entry(simple_frame)
simple_dialogue_label
TkinterExample.simple_dialogue_label = Label(simple_frame, text="Dialogue:")
simple_frame
TkinterExample.simple_frame = LabelFrame(app, text="Simple Format Options", padx=10, pady=10)
sticky
TkinterExample.sticky