Subtitle Display Tool: Subtitle-Display-Tool/src/util/util.h File Reference
util.h File Reference
#include <string>
#include <algorithm>
#include <cctype>
#include <locale>
Functions
template<class T >
T base_name (T const &path, T const &delims="/\\")
template<class T >
T remove_extension (T const &filename)
template<class T >
T file_extension (T const &filename)
std::string string_base_name (std::string const &path)
void ltrim (std::string &s)
void rtrim (std::string &s)
void trim (std::string &s)
std::string ltrim_copy (std::string s)
std::string rtrim_copy (std::string s)
std::string trim_copy (std::string s)
Function Documentation
base_name()
template<class T > T base_name (T const & path, T const & delims = "/\\")
Given a filepath, returns the file name with extension.
Referenced by string_base_name().
file_extension()
template<class T > T file_extension (T const & filename)
Given a filename (note: not a path), returns the file extension.
ltrim()
void ltrim (std::string & s) inline
From https://stackoverflow.com/a/217605
Referenced by ltrim_copy(), and trim().
ltrim_copy()
std::string ltrim_copy (std::string s) inline
References ltrim().
remove_extension()
template<class T > T remove_extension (T const & filename)
Given a filename (note: not a path), returns the base name without the file extension.
rtrim()
void rtrim (std::string & s) inline
Referenced by rtrim_copy(), and trim().
rtrim_copy()
std::string rtrim_copy (std::string s) inline
References rtrim().
string_base_name()
std::string string_base_name (std::string const & path) inline
References base_name().
trim()
void trim (std::string & s) inline
References ltrim(), and rtrim().
Referenced by trim_copy().
trim_copy()
std::string trim_copy (std::string s) inline
References trim().