Subtitle Display Tool: Subtitle-Display-Tool-Tests/WindowManagerTest.cpp File Reference
WindowManagerTest.cpp File Reference
#include "gtest/gtest.h"
#include "WindowManager.h"
Classes
class WindowManagerTest
Functions
std::vector< Window > & GetWindows (WindowManager &wm)
TEST_F (WindowManagerTest, AddWindowFromStack)
TEST_F (WindowManagerTest, AddWindowFromTemp)
Function Documentation
GetWindows()
std::vector<Window>& GetWindows (WindowManager & wm)
Referenced by TEST_F().
TEST_F() [1/2]
TEST_F (WindowManagerTest , AddWindowFromStack)
References GetWindows().
TEST_F() [2/2]
TEST_F (WindowManagerTest , AddWindowFromTemp)
References WindowManager::AddWindow(), and GetWindows().