name: Doxygen Update

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}